services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: ["5432:5432"]        # published so your IDE-run app can reach it
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm -d crm"]
      interval: 5s
      timeout: 3s
      retries: 10

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    ports: 
      - "8080:8080"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./certs/jwks.json:/etc/envoy/jwks.json:ro
volumes:
  pgdata:


#  command  containers  volume(data)
#  docker compose stop stopped kept
#  docker compose down deleted kept
#  docker compose down -v deleted deleted
#  docker compose start started kept
#  For connecting to database locally: docker compose exec postgres psql -U crm -d crm